# Generated by Django 3.2.8 on 2021-10-27 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('created_on',)},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published_on',
            new_name='created_on',
        ),
    ]
